name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      CODECOV_TOKEN : ${{ secrets.CODECOV_TOKEN }}

    name: Generate code coverage 
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v6
    - uses: SwiftyLab/setup-swift@latest
    
    - name: Run tests
      run: swift test --enable-code-coverage

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
